import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  fr: {
    nav_home: 'Accueil',
    nav_about: 'À Propos',
    nav_blog: 'Blog & Actualités',
    nav_contact: 'Contact',
    nav_login: 'Connexion',
    nav_register: 'Inscription',
    nav_admin_space: 'Espace Admin',
    nav_client_space: 'Mon Espace',
    nav_logout: 'Déconnexion',
    tunisia_label: 'Tunisie',
    lang_fr: 'Français',
    lang_en: 'English',
    lang_ar: 'العربية',
    tag_hero: 'Smart Tunisian Technoparks — Pôle El Ghazala',
    title_hero: 'Plateforme de Gestion des Contrats',
    title_hero_sub: '& de Facturation S2T',
    desc_hero: 'Le système centralisé dédié aux affaires juridiques, au suivi des contrats d\'hébergement, aux modifications de superficie et à la gestion financière des redevances locatives du Pôle Technologique El Ghazala.',

    // Home Page Translations
    home_badge: 'Pôle Technologique El Ghazala — S2T',
    home_hero_title: 'Gestion des Contrats',
    home_hero_title_sub: '& Facturation S2T',
    home_hero_desc: 'La plateforme officielle dédiée aux affaires juridiques, au suivi des conventions d\'hébergement (Articles 1 à 16), aux modifications de superficie et au recouvrement financier des redevances locatives.',
    home_btn_my_space: 'Accéder à votre Espace',
    home_role_admin: 'Administration',
    home_role_client: 'Entreprise',
    home_btn_resident: 'Espace Entreprise Hébergée',
    home_btn_legal: 'Portail Juridique & Finance',
    home_trust_law: 'Conforme Loi n°2001-50 & 2006-37',
    home_trust_rates: 'Tarifs réglementés (Art. 6)',
    home_trust_deposit: 'Dépôt de garantie sécurisé (Art. 7)',
    home_floating_address: 'Route de Raoued Km 3.5, Ariana',
    home_floating_companies_title: '250+ Sociétés Hébergées',
    home_floating_companies_sub: 'Pépinière & Pôle d\'Excellence TIC',

    // Stats
    home_stat_companies: 'Entreprises & Startups Hébergées',
    home_stat_engineers: 'Cadres & Ingénieurs TIC',
    home_stat_parks: 'Technoparcs Connectés en Tunisie',
    home_stat_occupancy: 'Taux d\'Occupation des Espaces',

    // Services / Prestations
    home_services_title: 'Services & Dispositif Contractuel',
    home_services_desc: 'Une offre complète encadrée par le contrat d\'hébergement au Pôle Technologique S2T (Articles 1 à 16).',
    home_service_1_title: 'Hébergement & Espaces Aménagés',
    home_service_1_desc: 'Bureaux équipés, pépinières d\'entreprises et plateaux modulables selon la superficie demandée (Art. 2 du contrat).',
    home_service_2_title: 'Gestion Juridique & Avenants',
    home_service_2_desc: 'Établissement des contrats d\'hébergement, renouvellements, résiliations et suivi des modifications de superficie (Art. 11).',
    home_service_3_title: 'Facturation & Suivi Financier',
    home_service_3_desc: 'Facturation automatisée des redevances, alertes d\'échéance au 5 du mois et suivi rigoureux des relances (J+15, J+30).',
    home_service_4_title: 'Prestations Complémentaires',
    home_service_4_desc: 'Connexion Internet très haut débit, salles de réunion et de formation, secrétariat mutualisé et gardiennage 24/7.',

    // Pricing / Bareme Art 6
    home_pricing_tag: 'Article 6 du Contrat d\'Hébergement',
    home_pricing_title: 'Grille Tarifaire des Redevances Locatives',
    home_pricing_desc: 'Tarification officielle par m² calculée selon l\'ancienneté en pépinière d\'entreprises.',
    home_badge_recommended: 'RECOMMANDÉ',
    home_tier_1_period: '1ère Année d\'Hébergement',
    home_tier_1_badge: 'Tarif Pépinière Phase 1',
    home_tier_1_desc: 'Tarif préférentiel d\'incubation pour les jeunes pousses et startups innovantes en phase d\'amorçage.',
    home_tier_2_period: '2ème Année d\'Hébergement',
    home_tier_2_badge: 'Tarif Pépinière Phase 2',
    home_tier_2_desc: 'Accompagnement dans la croissance avec accès élargi aux prestations mutualisées du pôle.',
    home_tier_3_period: '3ème Année & Plus',
    home_tier_3_badge: 'Tarif Consolidation',
    home_tier_3_desc: 'Tarif consolidé pour entreprises en phase d\'expansion technologique et partenariats industriels.',
    home_pricing_unit: 'HTVA / m² / an',
    home_pricing_note: '✓ Payable avant le 5 de chaque mois (Art. 6.3)',

    // Dual Portal CTA Box
    home_cta_title: 'Rejoignez le 1er Écosystème TIC en Tunisie',
    home_cta_desc: 'Que vous soyez une startup en quête d\'hébergement ou une entreprise résidente souhaitant consulter ses factures et conventions, accédez dès maintenant à votre espace.',
    home_btn_apply: 'Candidater à l\'Hébergement',
    home_btn_contact: 'Contacter la Direction',

    // About Page Translations
    about_badge: 'Histoire & Vision',
    about_title: 'À Propos de',
    about_title_sub: 'Smart Tunisian Technoparks',
    about_desc: 'Pionnier de l\'économie du savoir et premier pôle technologique en Tunisie, S2T impulse l\'innovation numérique, l\'hébergement d\'entreprises et la valorisation des compétences technologiques.',
    about_vocation_tag: 'Notre Vocation',
    about_vocation_title: 'Un catalyseur d\'innovation technologique au cœur du Maghreb',
    about_vocation_p1: 'Créé dans le cadre de la stratégie nationale de promotion des Technologies de l\'Information et de la Communication, S2T (Smart Tunisian Technoparks) gère notamment le prestigieux Pôle Technologique El Ghazala à l\'Ariana.',
    about_vocation_p2: 'S2T offre un environnement d\'affaires d\'excellence, doté d\'infrastructures de télécommunication de pointe, d\'un guichet unique administratif, juridique et financier pour accompagner les entreprises de l\'incubation jusqu\'au rayonnement international.',
    about_bullet_1: 'Conformité réglementaire aux lois n°2001-50 et n°2006-37',
    about_bullet_2: 'Partenariat étroit avec le Ministère des Technologies de la Communication',
    about_bullet_3: 'Gestion transparente des baux d\'hébergement & des redevances',
    about_stats_card_title: 'Chiffres Clés S2T',
    about_stats_card_sub: 'Impact National & International',
    about_stat_1_label: 'Superficie globale aménagée',
    about_stat_2_label: 'Sociétés résidentes',
    about_stat_3_label: 'Diplômés de l\'enseignement supérieur',
    about_stat_4_label: 'Année de création du pôle',
    about_missions_title: 'Nos Missions Stratégiques',
    about_missions_desc: 'Des engagements forts pour dynamiser l\'économie numérique tunisienne.',
    about_mission_1_title: 'Aménagement & Infrastructures Intelligentes',
    about_mission_1_desc: 'Conception et gestion d\'espaces bureautiques modernes, de pépinières et de centres de données adaptés aux exigences des multinationales et startups TIC.',
    about_mission_2_title: 'Incubation & Pépinière d\'Entreprises',
    about_mission_2_desc: 'Accompagnement juridique, technique et financier des porteurs de projets innovants avec des redevances locatives progressives et bonifiées.',
    about_mission_3_title: 'Animation de l\'Écosystème & Synergies',
    about_mission_3_desc: 'Création de passerelles directes entre les écoles d\'ingénieurs (Sup\'Com, INSAT, ENSI), les laboratoires de recherche et le tissu industriel.',
    about_mission_4_title: 'Cadre Juridique Sécurisé & Réglementaire',
    about_mission_4_desc: 'Application stricte des lois régissant les pôles technologiques (Loi n°2001-50 et Loi n°2006-37) pour garantir la pérennité contractuelle.',
    about_parks_title: 'Le Réseau National des Technoparcs',
    about_parks_desc: 'Un maillage territorial intelligent connecté pour favoriser l\'émergence de champions technologiques.',
    about_park_specialization: 'Spécialisation :',
    about_park_1_name: 'Pôle Technologique El Ghazala',
    about_park_1_city: 'Ariana / Grand Tunis',
    about_park_1_focus: 'Télécoms, Logiciels, IA & IoT',
    about_park_1_size: '65 Hectares',
    about_park_2_name: 'Technopark Manouba (Novation City)',
    about_park_2_city: 'Manouba',
    about_park_2_focus: 'Technologies Médicales & TIC',
    about_park_2_size: '52 Hectares',
    about_park_3_name: 'Technopôle de Sfax',
    about_park_3_city: 'Sfax',
    about_park_3_focus: 'Informatique & Multimédia',
    about_park_3_size: '40 Hectares',
    about_park_4_name: 'Technopôle de Sousse',
    about_park_4_city: 'Sousse',
    about_park_4_focus: 'Mécatronique & Électronique Intelligente',
    about_park_4_size: '56 Hectares',
    about_park_5_name: 'Technoparc de Bizerte',
    about_park_5_city: 'Bizerte',
    about_park_5_focus: 'Agro-alimentaire & Énergies Renouvelables',
    about_park_5_size: '35 Hectares',
    about_park_6_name: 'Technopôle de Médenine',
    about_park_6_city: 'Médenine',
    about_park_6_focus: 'Valorisation des Ressources Sahariennes',
    about_park_6_size: '30 Hectares',

    // Blog Page Translations
    blog_badge: 'Actualités & Publications',
    blog_title: 'Blog du',
    blog_title_sub: 'Pôle Technologique S2T',
    blog_desc: 'Retrouvez les dernières annonces, guides juridiques, appels à projets et actualités de l\'écosystème Smart Tunisian Technoparks.',
    blog_cat_all: 'Toutes les actualités',
    blog_cat_incubation: 'Incubation & Pépinière',
    blog_cat_juridique: 'Juridique & Réglementation',
    blog_cat_evenements: 'Événements & Salons',
    blog_cat_finance: 'Finance & Facturation',
    blog_search_placeholder: 'Rechercher un article...',
    blog_read_more: 'Lire l\'article',
    blog_by_author: 'Par',
    blog_close_modal: 'Fermer',
    blog_art1_title: 'Lancement de la nouvelle session d\'hébergement au Pôle El Ghazala 2026',
    blog_art1_date: '15 Mars 2026',
    blog_art1_read_time: '4 min de lecture',
    blog_art1_author: 'Direction de la Pépinière S2T',
    blog_art1_excerpt: 'S2T ouvre les candidatures pour les startups et PME innovantes souhaitant bénéficier d\'un bureau équipé à tarif bonifié (Article 6 : 30 DT/m² la première année).',
    blog_art1_content: `Le Pôle Technologique El Ghazala annonce l'ouverture officielle de l'appel à candidature pour l'intégration de la pépinière d'entreprises 2026.

Ce programme offre aux jeunes entreprises sélectionnées :
- Un local bureautique privatif avec charges comprises (Art. 2 du contrat d'hébergement).
- Une redevance annuelle bonifiée de 30,000 DT HTVA/m² pour la première année.
- Un accompagnement sur mesure pour la propriété intellectuelle, le financement et la mise en réseau.

Les dossiers de candidature doivent être soumis via le portail en ligne avant le 30 Avril 2026.`,
    blog_art2_title: 'Guide Pratique : Comprendre votre Contrat d\'Hébergement S2T (Articles 1 à 16)',
    blog_art2_date: '02 Mars 2026',
    blog_art2_read_time: '6 min de lecture',
    blog_art2_author: 'Service des Affaires Juridiques',
    blog_art2_excerpt: 'Tout savoir sur les obligations contractuelles, les modalités d\'avenant pour extension de surface et la constitution du dépôt de garantie (Article 7).',
    blog_art2_content: `Afin d'assurer une transparence totale avec les sociétés résidentes, le service juridique publie un guide détaillé expliquant chaque clause clé :

1. Prestations offertes & Charges (Article 2) :
L'accès aux espaces communs, le gardiennage 24/7, la fibre optique et les salles de réunion sont inclus dans le forfait de base.

2. Modalités de paiement (Article 6.3) :
La redevance mensuelle doit être réglée avant le 5 de chaque mois par virement ou ordre permanent.

3. Demandes d'Avenants (Article 11) :
Toute augmentation ou réduction de superficie nécessite la signature d'un avenant formalisé par les deux parties.`,
    blog_art3_title: 'Digitalisation des Factures & Suivi des Relances Automatisées',
    blog_art3_date: '20 Février 2026',
    blog_art3_read_time: '3 min de lecture',
    blog_art3_author: 'Direction Financière',
    blog_art3_excerpt: 'Mise en place de la plateforme de gestion unifiée permettant aux résidents de consulter en temps réel leurs factures, états de paiement et quittances.',
    blog_art3_content: `Dans le cadre de la modernisation de ses services, S2T déploie son portail financier intelligent. 

Les entreprises résidentes peuvent désormais :
- Télécharger leurs avis de paiement et factures certifiées en format PDF.
- Suivre le statut de leurs relances (J+15 et J+30) pour éviter tout intérêt de retard.
- Soumettre des demandes de justificatifs fiscaux en un clic.`,
    blog_art4_title: 'Forum National de l\'IA et de la Cybersécurité à El Ghazala',
    blog_art4_date: '10 Février 2026',
    blog_art4_read_time: '5 min de lecture',
    blog_art4_author: 'Pôle Communication',
    blog_art4_excerpt: 'Plus de 500 experts, chercheurs et dirigeants d\'entreprises réunis à l\'amphithéâtre S2T pour débattre des défis de l\'intelligence artificielle générative.',
    blog_art4_content: `Le Pôle El Ghazala a accueilli la 4ème édition du Forum National de l'IA. Cet événement a permis aux startups hébergées de présenter leurs solutions innovantes aux investisseurs et fonds de capital-risque tunisiens et internationaux.`,

    // Contact Page Translations
    contact_badge: 'Service Relations Résidents & Partenaires',
    contact_title: 'Contactez la',
    contact_title_sub: 'Direction S2T',
    contact_desc: 'Une équipe dédiée à votre écoute pour toute demande d\'hébergement, renseignement juridique ou suivi de facturation.',
    contact_info_title: 'Nos Coordonnées',
    contact_info_desc: 'Retrouvez nos services administratifs, juridiques et financiers au siège du Pôle El Ghazala.',
    contact_addr_title: 'Adresse Principale',
    contact_addr_val: 'Pôle Technologique El Ghazala, Route de Raoued Km 3.5, 2088 Ariana, Tunisie',
    contact_phone_title: 'Téléphone & Fax',
    contact_phone_standard: 'Standard :',
    contact_phone_fax: 'Fax :',
    contact_email_title: 'Emails Dédiés',
    contact_email_billing: 'Facturation :',
    contact_email_legal: 'Affaires Juridiques :',
    contact_hours_title: 'Horaires d\'Ouverture',
    contact_hours_val: 'Du Lundi au Vendredi : 08h00 — 17h00',
    contact_form_title: 'Envoyez-nous un Message',
    contact_form_desc: 'Remplissez le formulaire ci-dessous et notre équipe vous répondra sous 24h ouvrées.',
    contact_success_title: 'Message Envoyé avec Succès !',
    contact_success_sub: 'Votre demande a été transmise aux services compétents de S2T.',
    contact_field_name: 'Nom & Prénom *',
    contact_ph_name: 'ex: Ahmed Mansour',
    contact_field_company: 'Société / Startup',
    contact_ph_company: 'ex: DigitalTech',
    contact_field_email: 'Email Professionnel *',
    contact_ph_email: 'contact@societe.tn',
    contact_field_phone: 'Téléphone',
    contact_ph_phone: '+216 -- --- ---',
    contact_field_subject: 'Objet de la Demande',
    contact_opt_hosting: '🏢 Demande d\'hébergement & Superficie',
    contact_opt_legal: '⚖️ Affaires Juridiques & Contrat d\'Hébergement',
    contact_opt_billing: '💰 Facturation & Paiement de Redevance',
    contact_opt_amendment: '📝 Demande d\'Avenant / Modification de bail',
    contact_opt_other: '💬 Autre demande',
    contact_field_message: 'Message *',
    contact_ph_message: 'Précisez votre demande, la superficie souhaitée ou le numéro de contrat concerné...',
    contact_btn_send: 'Envoyer la Demande',
    contact_faq_badge: 'Foire Aux Questions',
    contact_faq_title: 'Questions Fréquentes des Entreprises',
    contact_faq1_q: 'Comment candidater pour un espace au Pôle El Ghazala ?',
    contact_faq1_a: 'Toute entreprise exerçant dans le secteur des TIC peut soumettre sa candidature en ligne via le bouton Inscription ou en transmettant son dossier d\'activité au service d\'incubation S2T.',
    contact_faq2_q: 'Comment s\'applique la tarification de la redevance (Article 6) ?',
    contact_faq2_a: 'La redevance locative annuelle est fixée selon l\'ancienneté en pépinière : 30 DT HTVA/m² pour la 1ère année, 55 DT HTVA/m² pour la 2ème année, et 75 DT HTVA/m² pour la 3ème année et au-delà.',
    contact_faq3_q: 'Quel est le montant du dépôt de garantie (Article 7) ?',
    contact_faq3_a: 'Le dépôt de garantie (caution) correspond à deux (2) mois de redevance locative TTC, versé sur le compte bancaire de la S2T auprès de l\'Agence Ariana Nord.',
    contact_faq4_q: 'Comment demander un avenant pour augmenter ou réduire ma superficie ?',
    contact_faq4_a: 'Les entreprises hébergées peuvent soumettre une demande d\'avenant directement depuis leur Espace Client (Dashboard). La demande est traitée par le service juridique et financier pour actualisation du contrat.',
    contact_faq5_q: 'Quels sont les délais de règlement des factures ?',
    contact_faq5_a: 'Conformément à l\'Article 6.3 du contrat d\'hébergement, les redevances sont payables d\'avance avant le 5 de chaque mois par ordre permanent ou virement bancaire.',

    // Login Page Translations
    login_title: 'Portail Sécurisé S2T',
    login_subtitle: 'Accédez à vos services de gestion de contrats & de facturation',
    login_tab_client: 'Entreprise Hébergée',
    login_tab_admin: 'Admin (Juridique/Finance)',
    login_label_email_client: 'Email de l\'entreprise hébergée',
    login_label_email_admin: 'Email administrateur S2T',
    login_label_password: 'Mot de passe',
    login_ph_email: 'votre.email@s2t.tn',
    login_ph_password: '••••••••',
    login_pending_title: 'Compte en attente d\'approbation',
    login_error_empty: 'Veuillez renseigner votre email et mot de passe',
    login_error_invalid: 'Identifiants incorrects ou serveur indisponible.',
    login_btn_loading: 'Authentification...',
    login_btn_submit_client: 'Se connecter (Espace Résident)',
    login_btn_submit_admin: 'Se connecter (Espace S2T)',
    login_demo_label: 'Compte Démo Actif :',
    login_demo_client: 'InnovTech (client@s2t.tn)',
    login_register_prompt: 'Nouvelle entreprise ?',
    login_register_link: 'Déposer une demande d\'hébergement',

    // Register Page Translations
    reg_title: "Demande d'Hébergement S2T",
    reg_subtitle: "Rejoignez l'écosystème technologique du Pôle El Ghazala",
    reg_logo_alt: "Logo S2T",
    reg_tab_client: "Entreprise Hébergée",
    reg_tab_admin: "Agent S2T (Direction)",
    reg_convention_banner_title: "Convention d'Hébergement Pôle S2T (16 Articles)",
    reg_convention_banner_desc: "Régie par la Loi n°2001-50 & 2006-37 • Redevances & Règlement Pépinière",
    reg_btn_read_articles: "Lire les 16 Articles",
    reg_label_company: "Raison Sociale / Société *",
    reg_ph_company: "ex: InnovTech SARL",
    reg_label_fiscal_id: "Matricule Fiscal",
    reg_ph_fiscal_id: "ex: 1234567/A/M/000",
    reg_label_activity: "Activité TIC (Loi 2001-50)",
    reg_act_software: "Édition Logiciels & IA",
    reg_act_telecom: "Télécoms & Réseaux",
    reg_act_cyber: "Cybersécurité & Cloud",
    reg_act_iot: "IoT & Systèmes Embarqués",
    reg_act_fintech: "FinTech & Services Numériques",
    reg_act_rd: "R&D et Innovation",
    reg_label_dept: "Département S2T",
    reg_dept_legal: "Service Affaires Juridiques",
    reg_dept_finance: "Direction Financière & Facturation",
    reg_dept_dg: "Direction Générale S2T",
    reg_label_surface: "Superficie souhaitée (m²)",
    reg_label_rep_name: "Nom du Représentant *",
    reg_ph_rep_name: "ex: Karim Ben Salem",
    reg_label_phone: "Téléphone",
    reg_ph_phone: "+216 -- --- ---",
    reg_label_email: "Email Professionnel *",
    reg_ph_email: "contact@societe.tn",
    reg_label_password: "Mot de passe (min. 6 car.) *",
    reg_label_confirm_pwd: "Confirmer mot de passe *",
    reg_ph_password: "••••••••",
    reg_checkbox_prefix: "J'atteste avoir pris connaissance de l'intégralité des",
    reg_checkbox_articles_bold: "16 articles de la Convention d'Hébergement S2T",
    reg_checkbox_and: "et du",
    reg_checkbox_rules_bold: "Règlement Intérieur",
    reg_checkbox_suffix: ", et j'en accepte les conditions (redevances, caution de 2 mois, destination TIC, obligations légales).",
    reg_checkbox_consult_link: "[Consulter les 16 Articles]",
    reg_btn_loading: "Traitement du dossier...",
    reg_btn_submit_client: "Soumettre ma Candidature Résident",
    reg_btn_submit_admin: "Créer le Compte Agent S2T",
    reg_already_account: "Vous avez déjà un compte validé ?",
    reg_link_login: "Se connecter",
    reg_err_required: "Veuillez remplir tous les champs obligatoires",
    reg_err_company: "Veuillez indiquer la raison sociale de votre entreprise",
    reg_err_articles: "Veuillez lire et accepter les 16 articles de la Convention d'Hébergement S2T pour soumettre votre dossier.",
    reg_err_pwd_length: "Le mot de passe doit comporter au moins 6 caractères",
    reg_err_pwd_match: "Les mots de passe ne correspondent pas",
    reg_err_default: "Erreur lors de la création du compte. Veuillez vérifier les informations saisies.",
    reg_success_badge: "Dossier Transmis • En attente d'approbation",
    reg_success_title: "Demande d'Hébergement Enregistrée !",
    reg_success_desc_prefix: "Votre candidature pour l'entreprise",
    reg_success_desc_suffix: "a été transmise à la Direction de Smart Tunisian Technoparks (S2T).",
    reg_recap_title: "Récapitulatif de votre demande",
    reg_recap_company: "Raison Sociale",
    reg_recap_rep: "Représentant Légal",
    reg_recap_email: "Email Professionnel",
    reg_recap_activity: "Activité TIC Éligible",
    reg_procedure_title: "Procédure d'admission (Loi n°2001-50 relative aux Parcs Technologiques) :",
    reg_procedure_desc_1: "Un administrateur de la",
    reg_procedure_desc_bold: "Direction Juridique & Financière S2T",
    reg_procedure_desc_2: "vérifie la conformité de votre activité TIC avec le cahier des charges du Pôle El Ghazala. Vous recevrez une notification d'activation dès l'approbation de votre dossier.",
    reg_convention_accepted_bold: "Convention d'Hébergement (16 Articles)",
    reg_convention_accepted_suffix: "consultée et acceptée.",
    reg_btn_reread_articles: "Relire les 16 Articles",
    reg_btn_to_login: "Page de Connexion",
    reg_btn_to_home: "Accueil S2T",
    reg_modal_title: "Convention d'Hébergement S2T — 16 Articles Réglementaires",
    articles_modal_default_title: "Convention d'Hébergement — 16 Articles Réglementaires S2T",
    articles_law_badge: "Loi n°2001-50 & 2006-37",
    articles_sub_header: "Smart Tunisian Technoparks (S2T) • Pôle Technologique El Ghazala",
    articles_print: "Imprimer",
    articles_print_tooltip: "Imprimer ou enregistrer en PDF",
    articles_close: "Fermer",
    articles_company_label: "Entreprise :",
    articles_resident_default: "Résident",
    articles_space_label: "Local :",
    articles_surface_label: "Superficie :",
    articles_rate_label: "Barème :",
    articles_search_ph: "Rechercher dans les 16 articles (ex: redevance, caution, préavis, résiliation...)",
    articles_quick_jump: "Accès direct à un article...",
    articles_articles_nav: "Articles :",
    articles_note_title: "Note Juridique Préalable (Pôle Technologique Smart Tunisian Technoparks) :",
    articles_note_p1: "La présente convention d'hébergement régit les rapports contractuels entre le",
    articles_note_p2: "Pôle S2T",
    articles_note_p3: "et l'",
    articles_note_p4: "entreprise hébergée",
    articles_note_p5: ". Conformément à la Loi n° 2001-50, elle constitue un contrat d'hébergement d'entreprise en pépinière / technoparc et n'est pas assujettie au statut des baux commerciaux de la loi du 25 mai 1977.",
    articles_no_results: "Aucun article ne correspond à votre recherche",
    articles_no_results_sub: "Essayez d'autres mots-clés ou réinitialisez le filtre.",
    articles_reset_filter: "Réinitialiser les filtres",
    articles_key_points: "Points Clés Juridiques :",
    articles_official_doc: "Document contractuel officiel approuvé par la Direction Générale S2T.",
    articles_btn_validated: "Conditions Validées ✓",
    articles_btn_accept: "J'ai lu et j'accepte les 16 Articles",

    // Footer
    footer_s2t_desc: 'Société de Gestion du Pôle Technologique El Ghazala. Aménagement, hébergement d\'entreprises et gestion des contrats d\'hébergement.',
    footer_nav: 'Navigation',
    footer_spaces: 'Espaces Dédiés',
    footer_contact_title: 'Contact',
    footer_contact_address: 'Pôle Technologique El Ghazala, Ariana',
    footer_copyright: 'Smart Tunisian Technoparks (S2T). Tous droits réservés.',
    footer_ministry: 'Sous tutelle du Ministère des Technologies de la Communication — République Tunisienne',
  },
  en: {
    nav_home: 'Home',
    nav_about: 'About Us',
    nav_blog: 'Blog & News',
    nav_contact: 'Contact Us',
    nav_login: 'Sign In',
    nav_register: 'Sign Up',
    nav_admin_space: 'Admin Space',
    nav_client_space: 'My Space',
    nav_logout: 'Logout',
    tunisia_label: 'Tunisia',
    lang_fr: 'Français',
    lang_en: 'English',
    lang_ar: 'العربية',
    tag_hero: 'Smart Tunisian Technoparks — El Ghazala Park',
    title_hero: 'Contracts & Billing Management',
    title_hero_sub: 'Platform for S2T',
    desc_hero: 'The centralized system dedicated to legal affairs, hosting contracts monitoring, area adjustments, and financial management of rental fees for El Ghazala Technopark.',

    // Home Page Translations
    home_badge: 'El Ghazala Technopark — S2T',
    home_hero_title: 'Contracts Management',
    home_hero_title_sub: '& S2T Billing',
    home_hero_desc: 'The official platform dedicated to legal affairs, hosting agreements monitoring (Articles 1 to 16), space adjustments, and financial collection of rental fees.',
    home_btn_my_space: 'Access your Portal',
    home_role_admin: 'Administration',
    home_role_client: 'Company',
    home_btn_resident: 'Resident Company Portal',
    home_btn_legal: 'Legal & Finance Portal',
    home_trust_law: 'Compliant with Law No. 2001-50 & 2006-37',
    home_trust_rates: 'Regulated Rates (Art. 6)',
    home_trust_deposit: 'Secured Guarantee Deposit (Art. 7)',
    home_floating_address: 'Raoued Road Km 3.5, Ariana',
    home_floating_companies_title: '250+ Hosted Companies',
    home_floating_companies_sub: 'Incubator & ICT Center of Excellence',

    // Stats
    home_stat_companies: 'Hosted Companies & Startups',
    home_stat_engineers: 'ICT Executives & Engineers',
    home_stat_parks: 'Connected Technoparks in Tunisia',
    home_stat_occupancy: 'Space Occupancy Rate',

    // Services / Prestations
    home_services_title: 'Services & Contractual Framework',
    home_services_desc: 'A comprehensive offering framed by the hosting agreement at S2T Technopark (Articles 1 to 16).',
    home_service_1_title: 'Hosting & Fitted Workspaces',
    home_service_1_desc: 'Equipped offices, business incubators, and modular workspaces tailored to requested areas (Art. 2 of contract).',
    home_service_2_title: 'Legal Management & Amendments',
    home_service_2_desc: 'Drafting hosting contracts, renewals, terminations, and monitoring surface area adjustments (Art. 11).',
    home_service_3_title: 'Invoicing & Financial Tracking',
    home_service_3_desc: 'Automated fee invoicing, due date alerts by the 5th of each month, and structured payment follow-ups (D+15, D+30).',
    home_service_4_title: 'Complementary Amenities',
    home_service_4_desc: 'High-speed fiber Internet, conference and training rooms, shared reception, and 24/7 security.',

    // Pricing / Bareme Art 6
    home_pricing_tag: 'Article 6 of Hosting Agreement',
    home_pricing_title: 'Official Rental Fees Schedule',
    home_pricing_desc: 'Official pricing per m² calculated according to incubation seniority in the technopark.',
    home_badge_recommended: 'RECOMMENDED',
    home_tier_1_period: '1st Year of Incubation',
    home_tier_1_badge: 'Incubator Rate Phase 1',
    home_tier_1_desc: 'Preferential incubation rate for early-stage startups and innovative tech ventures in seed phase.',
    home_tier_2_period: '2nd Year of Incubation',
    home_tier_2_badge: 'Incubator Rate Phase 2',
    home_tier_2_desc: 'Growth support with expanded access to shared technopark infrastructure and amenities.',
    home_tier_3_period: '3rd Year & Beyond',
    home_tier_3_badge: 'Consolidation Rate',
    home_tier_3_desc: 'Consolidated scale for established tech enterprises entering scaling and industrial partnerships.',
    home_pricing_unit: 'Excl. VAT / m² / yr',
    home_pricing_note: '✓ Due before the 5th of each month (Art. 6.3)',

    // Dual Portal CTA Box
    home_cta_title: 'Join the #1 ICT Tech Ecosystem in Tunisia',
    home_cta_desc: 'Whether you are a startup seeking office incubation or a resident company managing agreements and invoices, access your portal now.',
    home_btn_apply: 'Apply for Hosting',
    home_btn_contact: 'Contact Management',

    // About Page Translations
    about_badge: 'History & Vision',
    about_title: 'About',
    about_title_sub: 'Smart Tunisian Technoparks',
    about_desc: 'Pioneer of the knowledge economy and first technology park in Tunisia, S2T drives digital innovation, enterprise hosting, and the valorization of technological skills.',
    about_vocation_tag: 'Our Mission',
    about_vocation_title: 'A catalyst for technological innovation at the heart of the Maghreb',
    about_vocation_p1: 'Created within the national strategy for Information and Communication Technologies, S2T (Smart Tunisian Technoparks) notably manages the prestigious El Ghazala Technopark in Ariana.',
    about_vocation_p2: 'S2T offers a world-class business environment with advanced telecommunications infrastructure, a single administrative, legal, and financial desk to guide companies from incubation to international prominence.',
    about_bullet_1: 'Regulatory compliance with Laws No. 2001-50 & 2006-37',
    about_bullet_2: 'Close partnership with the Ministry of Communication Technologies',
    about_bullet_3: 'Transparent management of hosting leases & fee collection',
    about_stats_card_title: 'S2T Key Figures',
    about_stats_card_sub: 'National & International Impact',
    about_stat_1_label: 'Total fitted surface area',
    about_stat_2_label: 'Resident companies',
    about_stat_3_label: 'Higher education graduates',
    about_stat_4_label: 'Technopark foundation year',
    about_missions_title: 'Our Strategic Missions',
    about_missions_desc: 'Firm commitments to invigorate the Tunisian digital economy.',
    about_mission_1_title: 'Development & Smart Infrastructure',
    about_mission_1_desc: 'Design and management of modern office spaces, incubators, and data centers tailored to multinational and ICT startup requirements.',
    about_mission_2_title: 'Incubation & Business Acceleration',
    about_mission_2_desc: 'Legal, technical, and financial support for innovative project holders with progressive preferential rental rates.',
    about_mission_3_title: 'Ecosystem Animation & Synergies',
    about_mission_3_desc: 'Building direct bridges between engineering schools (Sup\'Com, INSAT, ENSI), research laboratories, and industry leaders.',
    about_mission_4_title: 'Secure Legal & Regulatory Framework',
    about_mission_4_desc: 'Strict enforcement of laws governing technology parks (Law No. 2001-50 & Law No. 2006-37) to guarantee contractual durability.',
    about_parks_title: 'National Technopark Network',
    about_parks_desc: 'An intelligent connected regional network to foster the rise of tech champions.',
    about_park_specialization: 'Specialization:',
    about_park_1_name: 'El Ghazala Technopark',
    about_park_1_city: 'Ariana / Greater Tunis',
    about_park_1_focus: 'Telecom, Software, AI & IoT',
    about_park_1_size: '65 Hectares',
    about_park_2_name: 'Manouba Technopark (Novation City)',
    about_park_2_city: 'Manouba',
    about_park_2_focus: 'Medical Technologies & ICT',
    about_park_2_size: '52 Hectares',
    about_park_3_name: 'Sfax Technopole',
    about_park_3_city: 'Sfax',
    about_park_3_focus: 'Computer Science & Multimedia',
    about_park_3_size: '40 Hectares',
    about_park_4_name: 'Sousse Technopole',
    about_park_4_city: 'Sousse',
    about_park_4_focus: 'Mechatronics & Smart Electronics',
    about_park_4_size: '56 Hectares',
    about_park_5_name: 'Bizerte Technopark',
    about_park_5_city: 'Bizerte',
    about_park_5_focus: 'Agri-food & Renewable Energies',
    about_park_5_size: '35 Hectares',
    about_park_6_name: 'Medenine Technopole',
    about_park_6_city: 'Medenine',
    about_park_6_focus: 'Saharan Resources Valorization',
    about_park_6_size: '30 Hectares',

    // Blog Page Translations
    blog_badge: 'News & Publications',
    blog_title: 'Blog of',
    blog_title_sub: 'S2T Technopark',
    blog_desc: 'Explore the latest announcements, legal guides, calls for proposals, and updates from the Smart Tunisian Technoparks ecosystem.',
    blog_cat_all: 'All News',
    blog_cat_incubation: 'Incubation & Hub',
    blog_cat_juridique: 'Legal & Regulation',
    blog_cat_evenements: 'Events & Expos',
    blog_cat_finance: 'Finance & Billing',
    blog_search_placeholder: 'Search an article...',
    blog_read_more: 'Read article',
    blog_by_author: 'By',
    blog_close_modal: 'Close',
    blog_art1_title: 'Launch of the 2026 Incubation Intake at El Ghazala Technopark',
    blog_art1_date: 'March 15, 2026',
    blog_art1_read_time: '4 min read',
    blog_art1_author: 'S2T Incubator Management',
    blog_art1_excerpt: 'S2T opens applications for tech startups and innovative SMEs looking for fitted offices at preferential rates (Art. 6: 30 TND/m² for the 1st year).',
    blog_art1_content: `El Ghazala Technopark officially announces the opening of the 2026 incubation application cycle.

Selected early-stage ventures will benefit from:
- Private fitted office space with utilities included (Art. 2 of Hosting Agreement).
- Preferential annual fee of 30.000 TND Excl. VAT/m² for the first year.
- Tailored advisory in IP protection, fundraising, and industry networking.

Applications must be submitted through the online portal before April 30, 2026.`,
    blog_art2_title: 'Practical Guide: Understanding your S2T Hosting Contract (Articles 1 to 16)',
    blog_art2_date: 'March 02, 2026',
    blog_art2_read_time: '6 min read',
    blog_art2_author: 'Legal Affairs Department',
    blog_art2_excerpt: 'Everything you need to know about contractual terms, surface extension amendments, and security deposit management (Article 7).',
    blog_art2_content: `To ensure full transparency with resident companies, the legal department publishes a detailed overview of key clauses:

1. Services & Utilities (Article 2):
Access to common areas, 24/7 security, high-speed fiber internet, and conference rooms are fully covered in the core agreement.

2. Payment Terms (Article 6.3):
Monthly fees must be settled prior to the 5th of each month via wire transfer or permanent order.

3. Contract Amendment Requests (Article 11):
Any increase or reduction in occupied space requires a formal contract amendment signed by both parties.`,
    blog_art3_title: 'Digital Invoices & Automated Payment Reminders',
    blog_art3_date: 'February 20, 2026',
    blog_art3_read_time: '3 min read',
    blog_art3_author: 'Finance Department',
    blog_art3_excerpt: 'Rollout of the unified portal enabling residents to check invoices, payment status, and tax receipts in real time.',
    blog_art3_content: `As part of its digital transformation, S2T introduces an intelligent financial portal.

Resident enterprises can now:
- Download official payment notices and certified invoices in PDF format.
- Monitor payment reminder timelines (D+15 and D+30) to prevent penalty fees.
- Submit tax clearance documentation requests with one click.`,
    blog_art4_title: 'National AI & Cybersecurity Forum at El Ghazala',
    blog_art4_date: 'February 10, 2026',
    blog_art4_read_time: '5 min read',
    blog_art4_author: 'Communications Division',
    blog_art4_excerpt: 'Over 500 tech leaders, researchers, and venture capitalists gathered at S2T auditorium to discuss generative AI advancements.',
    blog_art4_content: `El Ghazala Technopark hosted the 4th edition of the National AI Forum. This premier event gave hosted tech startups the opportunity to showcase innovations to regional and global venture capital funds.`,

    // Contact Page Translations
    contact_badge: 'Resident & Partner Relations Service',
    contact_title: 'Contact',
    contact_title_sub: 'S2T Management',
    contact_desc: 'A dedicated team at your service for hosting requests, legal inquiries, or billing assistance.',
    contact_info_title: 'Our Contact Details',
    contact_info_desc: 'Find our administrative, legal, and financial services at El Ghazala Technopark headquarters.',
    contact_addr_title: 'Main Address',
    contact_addr_val: 'El Ghazala Technopark, Raoued Road Km 3.5, 2088 Ariana, Tunisia',
    contact_phone_title: 'Phone & Fax',
    contact_phone_standard: 'Main Desk:',
    contact_phone_fax: 'Fax:',
    contact_email_title: 'Dedicated Emails',
    contact_email_billing: 'Billing:',
    contact_email_legal: 'Legal Affairs:',
    contact_hours_title: 'Opening Hours',
    contact_hours_val: 'Monday to Friday: 08:00 AM — 05:00 PM',
    contact_form_title: 'Send Us a Message',
    contact_form_desc: 'Fill out the form below and our team will get back to you within 24 business hours.',
    contact_success_title: 'Message Sent Successfully!',
    contact_success_sub: 'Your request has been forwarded to the competent S2T services.',
    contact_field_name: 'Full Name *',
    contact_ph_name: 'e.g. John Doe',
    contact_field_company: 'Company / Startup',
    contact_ph_company: 'e.g. DigitalTech',
    contact_field_email: 'Business Email *',
    contact_ph_email: 'contact@company.com',
    contact_field_phone: 'Phone Number',
    contact_ph_phone: '+216 -- --- ---',
    contact_field_subject: 'Subject of Request',
    contact_opt_hosting: '🏢 Hosting & Surface Area Request',
    contact_opt_legal: '⚖️ Legal Affairs & Hosting Agreement',
    contact_opt_billing: '💰 Invoicing & Fee Payment',
    contact_opt_amendment: '📝 Contract Amendment / Lease Modification',
    contact_opt_other: '💬 Other Inquiry',
    contact_field_message: 'Message *',
    contact_ph_message: 'Specify your request, desired area, or contract number...',
    contact_btn_send: 'Send Request',
    contact_faq_badge: 'Frequently Asked Questions',
    contact_faq_title: 'Frequently Asked Questions by Companies',
    contact_faq1_q: 'How to apply for an office space at El Ghazala Technopark?',
    contact_faq1_a: 'Any ICT-focused enterprise can submit an online application via the Sign Up button or by submitting their business proposal to the S2T incubator team.',
    contact_faq2_q: 'How is the rental fee scale applied (Article 6)?',
    contact_faq2_a: 'Annual rental fees are set according to incubation seniority: 30 TND Excl. VAT/m² for the 1st year, 55 TND Excl. VAT/m² for the 2nd year, and 75 TND Excl. VAT/m² for the 3rd year and beyond.',
    contact_faq3_q: 'What is the amount of the guarantee deposit (Article 7)?',
    contact_faq3_a: 'The guarantee deposit corresponds to two (2) months of rental fee incl. VAT, deposited into the S2T bank account at Ariana Nord Branch.',
    contact_faq4_q: 'How to request a contract amendment to increase or decrease my surface area?',
    contact_faq4_a: 'Resident companies can submit an amendment request directly through their Client Portal (Dashboard). Requests are reviewed by the legal and financial teams for contract update.',
    contact_faq5_q: 'What are the payment terms and deadlines for invoices?',
    contact_faq5_a: 'In accordance with Article 6.3 of the hosting agreement, rental fees are payable in advance before the 5th of each month via standing order or direct bank transfer.',

    // Login Page Translations
    login_title: 'S2T Secure Portal',
    login_subtitle: 'Access your contracts & billing management services',
    login_tab_client: 'Resident Company',
    login_tab_admin: 'Admin (Legal/Finance)',
    login_label_email_client: 'Resident company email',
    login_label_email_admin: 'S2T administrator email',
    login_label_password: 'Password',
    login_ph_email: 'your.email@s2t.tn',
    login_ph_password: '••••••••',
    login_pending_title: 'Account pending approval',
    login_error_empty: 'Please enter your email and password',
    login_error_invalid: 'Incorrect credentials or server unavailable.',
    login_btn_loading: 'Authenticating...',
    login_btn_submit_client: 'Sign In (Resident Portal)',
    login_btn_submit_admin: 'Sign In (S2T Portal)',
    login_demo_label: 'Active Demo Account:',
    login_demo_client: 'InnovTech (client@s2t.tn)',
    login_demo_admin: 'Management (admin@s2t.tn)',
    login_register_prompt: 'New enterprise?',
    login_register_link: 'Submit a hosting application',

    // Register Page Translations
    reg_title: "S2T Hosting Application",
    reg_subtitle: "Join the technology ecosystem of El Ghazala Technopark",
    reg_logo_alt: "S2T Logo",
    reg_tab_client: "Resident Company",
    reg_tab_admin: "S2T Agent (Management)",
    reg_convention_banner_title: "S2T Hosting Agreement (16 Articles)",
    reg_convention_banner_desc: "Governed by Law No. 2001-50 & 2006-37 • Fees & Incubator Regulations",
    reg_btn_read_articles: "Read the 16 Articles",
    reg_label_company: "Company / Corporate Name *",
    reg_ph_company: "e.g. InnovTech LLC",
    reg_label_fiscal_id: "Tax ID / Fiscal Matricule",
    reg_ph_fiscal_id: "e.g. 1234567/A/M/000",
    reg_label_activity: "ICT Activity (Law 2001-50)",
    reg_act_software: "Software Publishing & AI",
    reg_act_telecom: "Telecom & Networks",
    reg_act_cyber: "Cybersecurity & Cloud",
    reg_act_iot: "IoT & Embedded Systems",
    reg_act_fintech: "FinTech & Digital Services",
    reg_act_rd: "R&D and Innovation",
    reg_label_dept: "S2T Department",
    reg_dept_legal: "Legal Affairs Division",
    reg_dept_finance: "Finance & Billing Department",
    reg_dept_dg: "S2T Executive Management",
    reg_label_surface: "Desired Area (m²)",
    reg_label_rep_name: "Representative Name *",
    reg_ph_rep_name: "e.g. Karim Ben Salem",
    reg_label_phone: "Phone Number",
    reg_ph_phone: "+216 -- --- ---",
    reg_label_email: "Business Email *",
    reg_ph_email: "contact@company.tn",
    reg_label_password: "Password (min. 6 chars) *",
    reg_label_confirm_pwd: "Confirm Password *",
    reg_ph_password: "••••••••",
    reg_checkbox_prefix: "I certify having read and reviewed all",
    reg_checkbox_articles_bold: "16 articles of the S2T Hosting Agreement",
    reg_checkbox_and: "and the",
    reg_checkbox_rules_bold: "Internal Regulations",
    reg_checkbox_suffix: ", and I accept its terms (rental fees, 2-month deposit, ICT designation, legal obligations).",
    reg_checkbox_consult_link: "[View the 16 Articles]",
    reg_btn_loading: "Processing application...",
    reg_btn_submit_client: "Submit Resident Application",
    reg_btn_submit_admin: "Create S2T Agent Account",
    reg_already_account: "Already have an approved account?",
    reg_link_login: "Sign in here",
    reg_err_required: "Please fill in all mandatory fields",
    reg_err_company: "Please enter your company corporate name",
    reg_err_articles: "Please read and accept the 16 articles of the S2T Hosting Agreement to submit your application.",
    reg_err_pwd_length: "Password must contain at least 6 characters",
    reg_err_pwd_match: "Passwords do not match",
    reg_err_default: "Error while creating account. Please check the entered information.",
    reg_success_badge: "Application Submitted • Pending Approval",
    reg_success_title: "Hosting Application Registered!",
    reg_success_desc_prefix: "Your application for the company",
    reg_success_desc_suffix: "has been forwarded to the Management of Smart Tunisian Technoparks (S2T).",
    reg_recap_title: "Application Summary",
    reg_recap_company: "Company Name",
    reg_recap_rep: "Legal Representative",
    reg_recap_email: "Business Email",
    reg_recap_activity: "Eligible ICT Activity",
    reg_procedure_title: "Admission Procedure (Law No. 2001-50 on Technology Parks):",
    reg_procedure_desc_1: "An officer from the",
    reg_procedure_desc_bold: "S2T Legal & Financial Management",
    reg_procedure_desc_2: "will verify the compliance of your ICT activity with the El Ghazala Technopark criteria. You will receive an activation notification upon approval.",
    reg_convention_accepted_bold: "Hosting Agreement (16 Articles)",
    reg_convention_accepted_suffix: "viewed and accepted.",
    reg_btn_reread_articles: "Re-read the 16 Articles",
    reg_btn_to_login: "Login Page",
    reg_btn_to_home: "S2T Home",
    reg_modal_title: "S2T Hosting Agreement — 16 Regulatory Articles",
    articles_modal_default_title: "Hosting Agreement — 16 S2T Regulatory Articles",
    articles_law_badge: "Law No. 2001-50 & 2006-37",
    articles_sub_header: "Smart Tunisian Technoparks (S2T) • El Ghazala Technopark",
    articles_print: "Print",
    articles_print_tooltip: "Print or save as PDF",
    articles_close: "Close",
    articles_company_label: "Company:",
    articles_resident_default: "Resident",
    articles_space_label: "Office Space:",
    articles_surface_label: "Surface Area:",
    articles_rate_label: "Rate Schedule:",
    articles_search_ph: "Search in the 16 articles (e.g., fee, deposit, notice, termination...)",
    articles_quick_jump: "Direct access to an article...",
    articles_articles_nav: "Articles:",
    articles_note_title: "Preliminary Legal Notice (Smart Tunisian Technoparks):",
    articles_note_p1: "This hosting agreement governs the contractual relationship between the",
    articles_note_p2: "S2T Technopark",
    articles_note_p3: "and the",
    articles_note_p4: "hosted enterprise",
    articles_note_p5: ". In accordance with Law No. 2001-50, it constitutes an incubator/technopark hosting agreement and is not subject to commercial lease status under the law of May 25, 1977.",
    articles_no_results: "No articles match your search",
    articles_no_results_sub: "Try different keywords or reset the filter.",
    articles_reset_filter: "Reset Filters",
    articles_key_points: "Key Legal Highlights:",
    articles_official_doc: "Official contractual document approved by S2T Executive Management.",
    articles_btn_validated: "Terms Accepted ✓",
    articles_btn_accept: "I have read and agree to the 16 Articles",

    // Footer
    footer_s2t_desc: 'Management Company of El Ghazala Technopark. Urban development, enterprise hosting, and contractual lease administration.',
    footer_nav: 'Navigation',
    footer_spaces: 'Dedicated Portals',
    footer_contact_title: 'Contact',
    footer_contact_address: 'El Ghazala Technopark, Ariana',
    footer_copyright: 'Smart Tunisian Technoparks (S2T). All rights reserved.',
    footer_ministry: 'Under the supervision of the Ministry of Communication Technologies — Republic of Tunisia',
  },
  ar: {
    nav_home: 'الرئيسية',
    nav_about: 'من نحن',
    nav_blog: 'الأخبار والمستجدات',
    nav_contact: 'اتصل بنا',
    nav_login: 'تسجيل الدخول',
    nav_register: 'إنشاء حساب',
    nav_admin_space: 'فضاء الإدارة',
    nav_client_space: 'فضاء المقيم',
    nav_logout: 'تسجيل الخروج',
    tunisia_label: 'تونس',
    lang_fr: 'Français',
    lang_en: 'English',
    lang_ar: 'العربية',
    tag_hero: 'تونس للأقطاب التكنولوجية الذكية — قطب الغزالة',
    title_hero: 'منصة إدارة العقود',
    title_hero_sub: 'والفوترة S2T',
    desc_hero: 'المنظومة المركزية المخصصة للشؤون القانونية، ومتابعة عقود الإيواء وتعديلات المساحة والإدارة المالية للمستحقات الإيجارية بالقطب التكنولوجي الغزالة.',

    // Home Page Translations
    home_badge: 'القطب التكنولوجي الغزالة — S2T',
    home_hero_title: 'إدارة العقود',
    home_hero_title_sub: 'والفوترة S2T',
    home_hero_desc: 'المنصة الرسمية المخصصة للشؤون القانونية، ومتابعة اتفاقيات الإيواء (الفصول من 1 إلى 16)، وتعديلات المساحة، واستخلاص المستحقات الإيجارية.',
    home_btn_my_space: 'الدخول إلى فضائكم',
    home_role_admin: 'الإدارة',
    home_role_client: 'المؤسسة',
    home_btn_resident: 'فضاء المؤسسة المقيمة',
    home_btn_legal: 'بوابة الشؤون القانونية والمالية',
    home_trust_law: 'مطابق للقانون عدد 2001-50 و 2006-37',
    home_trust_rates: 'تسعيرات مقننة (الفصل 6)',
    home_trust_deposit: 'ضمان تأمين محمي (الفصل 7)',
    home_floating_address: 'طريق رواد كلم 3.5، أريانة',
    home_floating_companies_title: '+250 شركة مقيمة',
    home_floating_companies_sub: 'محضنة وقطب تميز في تكنولوجيا المعلومات',

    // Stats
    home_stat_companies: 'شركات ومؤسسات ناشئة مقيمة',
    home_stat_engineers: 'إطارات ومهندسو تكنولوجيا المعلومات',
    home_stat_parks: 'أقطاب تكنولوجية متصلة بتونس',
    home_stat_occupancy: 'نسبة إشغال المساحات',

    // Services / Prestations
    home_services_title: 'الخدمات والمنظومة التعاقدية',
    home_services_desc: 'عرض متكامل ومؤطر بعقد الإيواء بالقطب التكنولوجي S2T (الفصول من 1 إلى 16).',
    home_service_1_title: 'الإيواء والمساحات المهيأة',
    home_service_1_desc: 'مكاتب مجهزة، محاضن مؤسسات ومساحات قابلة للتقسيم والتعديل حسب المساحة المطلوبة (الفصل 2 من العقد).',
    home_service_2_title: 'الإدارة القانونية والملاحق',
    home_service_2_desc: 'إبرام عقود الإيواء، التجديدات، إنهاء العقود ومتابعة تعديلات المساحة والملاحق التعاقدية (الفصل 11).',
    home_service_3_title: 'الفوترة والمتابعة المالية',
    home_service_3_desc: 'فوترة آلية للمستحقات، تنبيهات الاستحقاق قبل اليوم الخامس من كل شهر ومتابعة التذكيرات (ي+15، ي+30).',
    home_service_4_title: 'الخدمات التكميلية والمشتركة',
    home_service_4_desc: 'إنترنت فائق السرعة عبر الألياف البصرية، قاعات اجتماعات وتدريب، أمانة عامة مشتركة وحراسة أمنية 24/7.',

    // Pricing / Bareme Art 6
    home_pricing_tag: 'الفصل 6 من عقد الإيواء',
    home_pricing_title: 'جدول التسعيرات الرسمية للمستحقات الإيجارية',
    home_pricing_desc: 'تسعيرة رسمية للمتر المربع محتسبة بدقة وفقاً لأقدمية المؤسسة في المحضنة التكنولوجية.',
    home_badge_recommended: 'موصى به',
    home_tier_1_period: 'السنة الأولى للإيواء',
    home_tier_1_badge: 'تسعيرة المحضنة المرحلة 1',
    home_tier_1_desc: 'تسعيرة تفاضلية لاحتضان الشركات الناشئة والمبتكرة في مرحلة الانطلاق والنمو الأولي.',
    home_tier_2_period: 'السنة الثانية للإيواء',
    home_tier_2_badge: 'تسعيرة المحضنة المرحلة 2',
    home_tier_2_desc: 'مرافقة في مرحلة تسريع النمو مع نفاذ موسع إلى كافة المرافق والخدمات المشتركة بالقطب.',
    home_tier_3_period: 'السنة الثالثة فما فوق',
    home_tier_3_badge: 'تسعيرة التثبيت',
    home_tier_3_desc: 'تسعيرة موحدة للمؤسسات في مرحلة التوسع التكنولوجي وإبرام الشراكات الصناعية.',
    home_pricing_unit: 'دون أداء / م² / سنوياً',
    home_pricing_note: '✓ تدفع قبل اليوم الخامس من كل شهر (الفصل 6.3)',

    // Dual Portal CTA Box
    home_cta_title: 'انضموا إلى المنظومة التكنولوجية الأولى في تونس',
    home_cta_desc: 'سواء كنتم مؤسسة ناشئة تبحث عن فضاء إيواء أو شركة مقيمة ترغب في الإطلاع على فواتيرها وعقودها، تفضلوا بالدخول إلى فضائكم الآن.',
    home_btn_apply: 'الترشح للإيواء بالقطب',
    home_btn_contact: 'الاتصال بالإدارة العامة',

    // About Page Translations
    about_badge: 'التاريخ والرؤية',
    about_title: 'حول',
    about_title_sub: 'تونس للأقطاب التكنولوجية الذكية',
    about_desc: 'رائد اقتصاد المعرفة وأول قطب تكنولوجي في تونس، تعمل S2T على دفع عجلة الابتكار الرقمي وإيواء المؤسسات وتثمين الكفاءات التكنولوجية.',
    about_vocation_tag: 'رسالتنا ومهمتنا',
    about_vocation_title: 'محفز للابتكار التكنولوجي في قلب المغرب العربي',
    about_vocation_p1: 'أُنشئت S2T في إطار الاستراتيجية الوطنية للنهوض بتكنولوجيات المعلومات والاتصال، وتشرف بشكل خاص على إدارة القطب التكنولوجي الغزالة العريق بأريانة.',
    about_vocation_p2: 'توفر S2T بيئة أعمال متميزة ومجهزة ببنية تحتية متطورة للاتصالات وشباك موحد إداري وقانوني ومالي لمرافقة المؤسسات من مرحلة الاحتضان إلى الإشعاع الدولي.',
    about_bullet_1: 'مطابقة تشريعية وتنظيمية للقانونين عدد 2001-50 وعدد 2006-37',
    about_bullet_2: 'شراكة وثيقة ومتواصلة مع وزارة تكنولوجيات الاتصال',
    about_bullet_3: 'إدارة شفافة لعقود الإيواء واستخلاص المستحقات الإيجارية',
    about_stats_card_title: 'أرقام ومؤشرات رئيسية S2T',
    about_stats_card_sub: 'إشعاع وأثر وطني ودولي',
    about_stat_1_label: 'إجمالي المساحة المهيأة',
    about_stat_2_label: 'مؤسسة مقيمة ومحتضنة',
    about_stat_3_label: 'خريجو التعليم العالي والجامعات',
    about_stat_4_label: 'سنة تأسيس وانطلاق القطب',
    about_missions_title: 'مهامنا الاستراتيجية',
    about_missions_desc: 'التزامات قوية وراسخة لتنشيط ودفع الاقتصاد الرقمي التونسي.',
    about_mission_1_title: 'التهيئة والبنية التحتية الذكية',
    about_mission_1_desc: 'تصميم وإدارة مساحات مكتبية عصرية ومحاضن مؤسسات ومراكز بيانات متطورة تلبي متطلبات الشركات العالمية والناشئة.',
    about_mission_2_title: 'الاحتضان ومحاضن المؤسسات',
    about_mission_2_desc: 'مرافقة قانونية وفنية ومالية لحاملي المشاريع المبتكرة مع تسعيرات إيجارية تفاضلية وتصاعدية.',
    about_mission_3_title: 'تنشيط المنظومة وخلق التكامل',
    about_mission_3_desc: 'بناء جسور مباشرة بين مدارس المهندسين (Sup\'Com، INSAT، ENSI) ومخابر البحث والنسيج الصناعي.',
    about_mission_4_title: 'إطار قانوني وتشريعي آمن',
    about_mission_4_desc: 'تطبيق صارم للقوانين المنظمة للأقطاب التكنولوجية (القانون عدد 2001-50 و2006-37) لضمان الاستقرار التعاقدي.',
    about_parks_title: 'الشبكة الوطنية للأقطاب التكنولوجية',
    about_parks_desc: 'شبكة وطنية متصلة وذكية لتشجيع بزوغ رواد التكنولوجيا والابتكار.',
    about_park_specialization: 'مجال التخصص :',
    about_park_1_name: 'القطب التكنولوجي الغزالة',
    about_park_1_city: 'أريانة / تونس الكبرى',
    about_park_1_focus: 'الاتصالات، البرمجيات، الذكاء الاصطناعي وإنترنت الأشياء',
    about_park_1_size: '65 هكتار',
    about_park_2_name: 'القطب التكنولوجي بمنوبة (Novation City)',
    about_park_2_city: 'منوبة',
    about_park_2_focus: 'التكنولوجيات الطبية وتكنولوجيا المعلومات',
    about_park_2_size: '52 هكتار',
    about_park_3_name: 'القطب التكنولوجي بصفاقس',
    about_park_3_city: 'صفاقس',
    about_park_3_focus: 'الإعلامية والوسائط المتعددة',
    about_park_3_size: '40 هكتار',
    about_park_4_name: 'القطب التكنولوجي بسوسة',
    about_park_4_city: 'سوسة',
    about_park_4_focus: 'الميكاترونيك والإلكترونيك الذكي',
    about_park_4_size: '56 هكتار',
    about_park_5_name: 'القطب التكنولوجي ببنزرت',
    about_park_5_city: 'بنزرت',
    about_park_5_focus: 'الصناعات الغذائية والطاقات المتجددة',
    about_park_5_size: '35 هكتار',
    about_park_6_name: 'القطب التكنولوجي بمدنين',
    about_park_6_city: 'مدنين',
    about_park_6_focus: 'تثمين الموارد الصحراوية والطبيعية',
    about_park_6_size: '30 هكتار',

    // Blog Page Translations
    blog_badge: 'الأخبار والمنشورات',
    blog_title: 'مدونة',
    blog_title_sub: 'القطب التكنولوجي S2T',
    blog_desc: 'تابعوا أحدث البلاغات، الأدلة القانونية، طلبات العروض ومستجدات منظومة تونس للأقطاب التكنولوجية الذكية.',
    blog_cat_all: 'كافة الأخبار والمستجدات',
    blog_cat_incubation: 'الاحتضان ومحضنة المؤسسات',
    blog_cat_juridique: 'الشؤون القانونية والتنظيمية',
    blog_cat_evenements: 'التظاهرات والمعارض',
    blog_cat_finance: 'المالية والفوترة',
    blog_search_placeholder: 'ابحث عن مقال أو بلاغ...',
    blog_read_more: 'قراءة المقال بالكامل',
    blog_by_author: 'بقلم',
    blog_close_modal: 'إغلاق',
    blog_art1_title: 'إطلاق دورة الاحتضان الجديدة بالقطب التكنولوجي الغزالة 2026',
    blog_art1_date: '15 مارس 2026',
    blog_art1_read_time: '4 دقائق قراءة',
    blog_art1_author: 'إدارة محضنة المؤسسات S2T',
    blog_art1_excerpt: 'تعلن S2T عن فتح باب الترشح للشركات الناشئة والمؤسسات المبتكرة للانتفاع بمكاتب مجهزة بتسعيرة تفاضلية مدعمة (الفصل 6 : 30 د.ت/م² للسنة الأولى).',
    blog_art1_content: `يعلن القطب التكنولوجي الغزالة رسمياً عن فتح باب الترشحات للانضمام إلى محضنة المؤسسات لسنة 2026.

يوفر هذا البرنامج للمؤسسات المختارة :
- محلاً مكتبياً مجهزاً وخاصاً مع شمول كافة المصاريف المشتركة (الفصل 2 من عقد الإيواء).
- تسعيرة سنوية تفاضلية وممتازة بقيمة 30.000 د.ت دون أداء/م² للسنة الأولى.
- مرافقة وتوجيه مخصص في مجال الملكية الفكرية، التمويل وربط الشبكات والشراكات.

يجب إيداع مطالب الترشح عبر المنصة الرقمية قبل تاريخ 30 أفريل 2026.`,
    blog_art2_title: 'دليل إرشادي : فهم عقد الإيواء بالقطب التكنولوجي S2T (الفصول من 1 إلى 16)',
    blog_art2_date: '02 مارس 2026',
    blog_art2_read_time: '6 دقائق قراءة',
    blog_art2_author: 'مصلحة الشؤون القانونية',
    blog_art2_excerpt: 'كل ما يجب معرفته حول الالتزامات التعاقدية، إجراءات إبرام ملحق لتوسيع المساحة وتكوين مبلغ ضمان التأمين (الفصل 7).',
    blog_art2_content: `سعياً لضمان الشفافية التامة مع المؤسسات المقيمة، تنشر المصلحة القانونية دليلاً تفصيلياً يوضح أبرز البنود التعاقدية :

1. الخدمات المقدمة والمصاريف (الفصل 2) :
النفاذ إلى الفضاءات المشتركة، الحراسة على مدار الساعة 24/7، الإنترنت فائق السرعة عبر الألياف البصرية وقاعات الاجتماعات مشمولة بالكامل في العقد.

2. صيغ وطرق الدفع والخلاص (الفصل 6.3) :
تدفع المستحقات الشهرية للإيواء مسبقاً قبل اليوم الخامس من كل شهر بواسطة تحويل بنكي أو إذن اقتطاع دائم.

3. طلبات الملاحق التعاقدية (الفصل 11) :
تتطلب أي زيادة في المساحة أو تقليص منها إبرام ملحق تعاقدي رسمي موقع ومصادق عليه من الطرفين.`,
    blog_art3_title: 'رقمنة الفواتير والمتابعة الآلية للتذكيرات والإشعارات',
    blog_art3_date: '20 فيفري 2026',
    blog_art3_read_time: '3 دقائق قراءة',
    blog_art3_author: 'الإدارة المالية',
    blog_art3_excerpt: 'إرساء المنصة الموحدة التي تتيح للمقيمين الإطلاع الفوري والحيني على فواتيرهم، كشوفات الدفع والإبراءات الجبائية.',
    blog_art3_content: `في إطار عصرنة وتحديث خدماتها، تطلق S2T بوابتها المالية الرقمية الذكية.

يمكن للمؤسسات المقيمة الآن :
- تنزيل إشعارات الدفع والفواتير المعتمدة بصيغة PDF.
- متابعة مسار التذكيرات (ي+15 و ي+30) لتفادي أي فوائض أو غرامات تأخير.
- إيداع طلبات الحصول على الوثائق المحاسبية والجبائية بنقرة واحدة.`,
    blog_art4_title: 'المنتدى الوطني للذكاء الاصطناعي والأمن السيبراني بقطب الغزالة',
    blog_art4_date: '10 فيفري 2026',
    blog_art4_read_time: '5 دقائق قراءة',
    blog_art4_author: 'خلية الاتصال والإعلام',
    blog_art4_excerpt: 'أكثر من 500 خبير وباحث وقادة أعمال التأموا بمدرج S2T لتدارس آفاق الذكاء الاصطناعي التوليدي.',
    blog_art4_content: `احتضن القطب التكنولوجي الغزالة الدورة الرابعة للمنتدى الوطني للذكاء الاصطناعي. وقد شكلت هذه التظاهرة فرصة مميزة للشركات الناشئة المحتضنة لعرض حلولها المبتكرة أمام المستثمرين وصناديق رأس المال الاستثماري التونسية والدولية.`,

    // Contact Page Translations
    contact_badge: 'مصلحة العلاقات مع المقيمين والشركاء',
    contact_title: 'اتصلوا بـ',
    contact_title_sub: 'الإدارة العامة S2T',
    contact_desc: 'فريق متخصص ومجند للإجابة عن استفساراتكم المتعلقة بالإيواء والشؤون القانونية ومتابعة الفواتير.',
    contact_info_title: 'بيانات الاتصال بنا',
    contact_info_desc: 'تفضلوا بزيارة مصالحنا الإدارية والقانونية والمالية بالمقر الرئيسي لقطب الغزالة.',
    contact_addr_title: 'المقر الرئيسي',
    contact_addr_val: 'القطب التكنولوجي الغزالة، طريق رواد كلم 3.5، 2088 أريانة، تونس',
    contact_phone_title: 'الهاتف والفاكس',
    contact_phone_standard: 'الموزع :',
    contact_phone_fax: 'الفاكس :',
    contact_email_title: 'عناوين البريد الإلكتروني',
    contact_email_billing: 'الفوترة :',
    contact_email_legal: 'الشؤون القانونية :',
    contact_hours_title: 'أوقات العمل الرسمية',
    contact_hours_val: 'من الإثنين إلى الجمعة : 08:00 — 17:00',
    contact_form_title: 'أرسلوا لنا رسالة',
    contact_form_desc: 'يرجى تعمير الاستمارة وسيجيبكم فريقنا في غضون 24 ساعة عمل.',
    contact_success_title: 'تم إرسال الرسالة بنجاح !',
    contact_success_sub: 'تم تحويل طلبكم بنجاح إلى المصالح المختصة لـ S2T.',
    contact_field_name: 'الاسم واللقب *',
    contact_ph_name: 'مثال: أحمد منصور',
    contact_field_company: 'المؤسسة / الشركة الناشئة',
    contact_ph_company: 'مثال: ديجيتال تيك',
    contact_field_email: 'البريد الإلكتروني المهني *',
    contact_ph_email: 'contact@societe.tn',
    contact_field_phone: 'رقم الهاتف',
    contact_ph_phone: '+216 -- --- ---',
    contact_field_subject: 'موضوع الطلب',
    contact_opt_hosting: '🏢 طلب إيواء ومساحة مكتبية',
    contact_opt_legal: '⚖️ الشؤون القانونية وعقد الإيواء',
    contact_opt_billing: '💰 الفوترة ودفع المستحقات الإيجارية',
    contact_opt_amendment: '📝 طلب ملحق تعاقدي / تعديل المساحة',
    contact_opt_other: '💬 استفسار آخر',
    contact_field_message: 'نص الرسالة *',
    contact_ph_message: 'يرجى توضيح طلبكم، المساحة المطلوبة أو رقم العقد المعني...',
    contact_btn_send: 'إرسال الطلب',
    contact_faq_badge: 'الأسئلة الشائعة',
    contact_faq_title: 'الأسئلة الأكثر تداولاً من قبل المؤسسات',
    contact_faq1_q: 'كيف يمكن تقديم مطلب ترشح للحصول على فضاء بالقطب التكنولوجي الغزالة ؟',
    contact_faq1_a: 'يمكن لأي مؤسسة تنشط في قطاع تكنولوجيات المعلومات والاتصال تقديم ترشحها عبر الضغط على زر التسجيل أو إرسال ملف نشاطها إلى مصلحة الاحتضان بـ S2T.',
    contact_faq2_q: 'كيف يتم احتساب وتطبيق تسعيرة المستحقات الإيجارية (الفصل 6) ؟',
    contact_faq2_a: 'تحدد التسعيرة السنوية وفقاً لأقدمية المؤسسة بالمحضنة: 30 د.ت دون أداء/م² للسنة الأولى، 55 د.ت دون أداء/م² للسنة الثانية، و75 د.ت دون أداء/م² للسنة الثالثة فما فوق.',
    contact_faq3_q: 'ما هي قيمة ومبلغ ضمان التأمين (الفصل 7) ؟',
    contact_faq3_a: 'يعادل ضمان التأمين (الضمانة) ما قيمته شهرين (2) من معين الإيواء مع احتساب كافة الأداءات، ويتم دفعه في الحساب البنكي لـ S2T لدى فرع أريانة الشمالية.',
    contact_faq4_q: 'كيف يمكن طلب ملحق تعاقدي للزيادة في المساحة أو التخفيض منها ؟',
    contact_faq4_a: 'تستطيع المؤسسات المقيمة تقديم طلب ملحق مباشرة من فضائها الخاص (لوحة التحكم). وتتولى المصلحة القانونية والمالية دراسة الطلب وتحيين العقد.',
    contact_faq5_q: 'ما هي الآجال القانونية لخلاص وتسوية الفواتير الإيجارية ؟',
    contact_faq5_a: 'طبقاً لمقتضيات الفصل 6.3 من عقد الإيواء، تدفع المستحقات مسبقاً قبل اليوم الخامس من كل شهر بواسطة إذن اقتطاع دائم أو تحويل بنكي.',

    // Login Page Translations
    login_title: 'بوابة S2T المؤمنة',
    login_subtitle: 'الدخول إلى خدمات إدارة العقود والفوترة',
    login_tab_client: 'المؤسسة المقيمة',
    login_tab_admin: 'الإدارة (القانونية/المالية)',
    login_label_email_client: 'البريد الإلكتروني للمؤسسة المقيمة',
    login_label_email_admin: 'البريد الإلكتروني لإدارة S2T',
    login_label_password: 'كلمة المرور',
    login_ph_email: 'votre.email@s2t.tn',
    login_ph_password: '••••••••',
    login_pending_title: 'الحساب في انتظار الموافقة',
    login_error_empty: 'يرجى إدخال البريد الإلكتروني وكلمة المرور',
    login_error_invalid: 'بيانات الدخول غير صحيحة أو الخادم غير متوفر.',
    login_btn_loading: 'جارٍ التحقق...',
    login_btn_submit_client: 'تسجيل الدخول (فضاء المقيم)',
    login_btn_submit_admin: 'تسجيل الدخول (فضاء الإدارة)',
    login_demo_label: 'حساب تجريبي مفعل :',
    login_demo_client: 'InnovTech (client@s2t.tn)',
    login_demo_admin: 'الإدارة العامة (admin@s2t.tn)',
    login_register_prompt: 'مؤسسة جديدة ؟',
    login_register_link: 'تقديم مطلب إيواء بالقطب',

    // Register Page Translations
    reg_title: "طلب إيواء بالقطب التكنولوجي S2T",
    reg_subtitle: "انضموا إلى المنظومة التكنولوجية للقطب التكنولوجي الغزالة",
    reg_logo_alt: "شعار S2T",
    reg_tab_client: "المؤسسة المقيمة",
    reg_tab_admin: "إطار S2T (الإدارة)",
    reg_convention_banner_title: "اتفاقية الإيواء بالقطب التكنولوجي S2T (16 فصلاً)",
    reg_convention_banner_desc: "خاضعة للقانونين عدد 2001-50 و 2006-37 • المعاليم والنظام الداخلي للمحضنة",
    reg_btn_read_articles: "قراءة الفصول الـ 16",
    reg_label_company: "الاسم التجاري / الشركة *",
    reg_ph_company: "مثال: إنوف تيك ش.م.م",
    reg_label_fiscal_id: "المعرف الجبائي",
    reg_ph_fiscal_id: "مثال: 1234567/A/M/000",
    reg_label_activity: "النشاط التكنولوجي (قانون 2001-50)",
    reg_act_software: "تطوير البرمجيات والذكاء الاصطناعي",
    reg_act_telecom: "الاتصالات والشبكات",
    reg_act_cyber: "الأمن السيبراني والحوسبة السحابية",
    reg_act_iot: "إنترنت الأشياء والأنظمة المدمجة",
    reg_act_fintech: "التكنولوجيا المالية والخدمات الرقمية",
    reg_act_rd: "البحث والتطوير والابتكار",
    reg_label_dept: "إدارة S2T",
    reg_dept_legal: "مصلحة الشؤون القانونية",
    reg_dept_finance: "الإدارة المالية والفوترة",
    reg_dept_dg: "الإدارة العامة S2T",
    reg_label_surface: "المساحة المطلوبة (م²)",
    reg_label_rep_name: "اسم ولقب الممثل القانوني *",
    reg_ph_rep_name: "مثال: كريم بن سالم",
    reg_label_phone: "رقم الهاتف",
    reg_ph_phone: "+216 -- --- ---",
    reg_label_email: "البريد الإلكتروني المهني *",
    reg_ph_email: "contact@societe.tn",
    reg_label_password: "كلمة المرور (6 أحرف على الأقل) *",
    reg_label_confirm_pwd: "تأكيد كلمة المرور *",
    reg_ph_password: "••••••••",
    reg_checkbox_prefix: "أقر باطلاعي التام على كافة",
    reg_checkbox_articles_bold: "الفصول الـ 16 لاتفاقية الإيواء S2T",
    reg_checkbox_and: "وعلى",
    reg_checkbox_rules_bold: "النظام الداخلي",
    reg_checkbox_suffix: "، وأوافق على كافة الشروط (المستحقات الإيجارية، ضمان شهرين، التخصيص التكنولوجي، الالتزامات القانونية).",
    reg_checkbox_consult_link: "[الإطلاع على الفصول الـ 16]",
    reg_btn_loading: "جارٍ معالجة الملف...",
    reg_btn_submit_client: "إيداع مطلب الترشح للإيواء",
    reg_btn_submit_admin: "إنشاء حساب إطار S2T",
    reg_already_account: "هل لديكم حساب مفعل بالفعل ؟",
    reg_link_login: "تسجيل الدخول",
    reg_err_required: "يرجى تعمير كافة الحقول الإجبارية",
    reg_err_company: "يرجى إدخال الاسم التجاري للشركة",
    reg_err_articles: "يرجى قراءة والموافقة على الفصول الـ 16 لاتفاقية الإيواء لتقديم ملفكم.",
    reg_err_pwd_length: "يجب ألا تقل كلمة المرور عن 6 أحرف",
    reg_err_pwd_match: "كلمتا المرور غير متطابقتين",
    reg_err_default: "حدث خطأ أثناء إنشاء الحساب. يرجى التثبت من صحة البيانات المدخلة.",
    reg_success_badge: "تم إرسال الملف • في انتظار الموافقة",
    reg_success_title: "تم تسجيل مطلب الإيواء بنجاح !",
    reg_success_desc_prefix: "تمت إحالة ملف ترشح المؤسسة",
    reg_success_desc_suffix: "إلى الإدارة العامة لتونس للأقطاب التكنولوجية الذكية (S2T).",
    reg_recap_title: "ملخص مطلبكم",
    reg_recap_company: "الاسم التجاري",
    reg_recap_rep: "الممثل القانوني",
    reg_recap_email: "البريد الإلكتروني المهني",
    reg_recap_activity: "النشاط التكنولوجي المؤهل",
    reg_procedure_title: "إجراءات القبول (القانون عدد 2001-50 المتعلق بالأقطاب التكنولوجية) :",
    reg_procedure_desc_1: "يتولى إطار من",
    reg_procedure_desc_bold: "الإدارة القانونية والمالية لـ S2T",
    reg_procedure_desc_2: "التثبت من مطابقة نشاطكم التكنولوجي لكراس الشروط الخاص بقطب الغزالة. ستتلقون إشعار تفعيل الحساب فور الموافقة على الملف.",
    reg_convention_accepted_bold: "اتفاقية الإيواء (16 فصلاً)",
    reg_convention_accepted_suffix: "تمت مراجعتها والموافقة عليها.",
    reg_btn_reread_articles: "إعادة قراءة الفصول الـ 16",
    reg_btn_to_login: "صفحة تسجيل الدخول",
    reg_btn_to_home: "الرئيسية S2T",
    reg_modal_title: "اتفاقية الإيواء بالقطب S2T — الفصول التنظيمية الـ 16",
    articles_modal_default_title: "اتفاقية الإيواء — الفصول التنظيمية الـ 16 لـ S2T",
    articles_law_badge: "القانون عدد 2001-50 و 2006-37",
    articles_sub_header: "تونس للأقطاب التكنولوجية الذكية (S2T) • القطب التكنولوجي الغزالة",
    articles_print: "طباعة",
    articles_print_tooltip: "طباعة أو حفظ بصيغة PDF",
    articles_close: "إغلاق",
    articles_company_label: "المؤسسة :",
    articles_resident_default: "المقيم",
    articles_space_label: "المحل :",
    articles_surface_label: "المساحة :",
    articles_rate_label: "جدول التسعير :",
    articles_search_ph: "بحث في الفصول الـ 16 (مثال: المستحقات، الضمان، الإنهاء، الإشعار...)",
    articles_quick_jump: "الوصول المباشر إلى فصل...",
    articles_articles_nav: "الفصول :",
    articles_note_title: "ملاحظة قانونية تمهيدية (القطب التكنولوجي تونس للأقطاب الذكية) :",
    articles_note_p1: "تنظم هذه الاتفاقية العلاقات التعاقدية بين",
    articles_note_p2: "قطب S2T",
    articles_note_p3: "و",
    articles_note_p4: "المؤسسة المقيمة",
    articles_note_p5: ". طبقاً للقانون عدد 2001-50، تعتبر عقد إيواء مؤسسة بمحضنة / قطب تكنولوجي ولا تخضع لأحكام عقود الكراء التجاري لقانون 25 ماي 1977.",
    articles_no_results: "لا توجد فصول تطابق بحثكم",
    articles_no_results_sub: "يرجى تجربة كلمات مفتاحية أخرى أو إعادة تعيين الفلتر.",
    articles_reset_filter: "إعادة ضبط الفلاتر",
    articles_key_points: "النقاط القانونية الرئيسية :",
    articles_official_doc: "وثيقة تعاقدية رسمية مصادق عليها من قبل الإدارة العامة لـ S2T.",
    articles_btn_validated: "الشروط مقبولة ومصادق عليها ✓",
    articles_btn_accept: "اطلعت وأوافق على الفصول الـ 16",

    // Footer
    footer_s2t_desc: 'شركة التصرف في القطب التكنولوجي الغزالة. تهيئة، إيواء المؤسسات وإدارة عقود الإيواء.',
    footer_nav: 'التصفح',
    footer_spaces: 'الفضاءات المخصصة',
    footer_contact_title: 'الاتصال',
    footer_contact_address: 'القطب التكنولوجي الغزالة، أريانة',
    footer_copyright: 'تونس للأقطاب التكنولوجية الذكية (S2T). جميع الحقوق محفوظة.',
    footer_ministry: 'تحت إشراف وزارة تكنولوجيات الاتصال — الجمهورية التونسية',
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('s2t_language') || 'fr';
  });

  useEffect(() => {
    localStorage.setItem('s2t_language', language);
    if (language === 'ar') {
      document.documentElement.setAttribute('dir', 'rtl');
      document.documentElement.setAttribute('lang', 'ar');
    } else {
      document.documentElement.setAttribute('dir', 'ltr');
      document.documentElement.setAttribute('lang', language);
    }
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations['fr']?.[key] || key;
  };

  const languages = [
    { code: 'fr', label: 'Français', flagImg: '/france-flag.svg', native: 'Français' },
    { code: 'en', label: 'English', flagImg: '/us-flag.svg', native: 'English (US)' },
    { code: 'ar', label: 'العربية', flagImg: '/tunisia-flag.svg', native: 'العربية (تونس)' },
  ];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languages }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
